package org.example.skills.enums;

public enum AuditAction {

    CASH_INCOME,
    CASH_EXPENSE,

    CHECK_IN,
    CHECK_COLLECT,
    CHECK_ENDORSE,
    CHECK_OUT,
    CHECK_PAID,

    NOTE_IN,
    NOTE_COLLECT,
    NOTE_ENDORSE,
    NOTE_OUT,

    LOAN_CREATE,
    LOAN_INSTALLMENT,

    CASH_UPDATE_REQUEST_CREATED,
    CASH_UPDATE_REQUEST_APPROVED,
    CASH_UPDATE_REQUEST_REJECTED,

    CHECK_UPDATE_REQUEST_CREATED,
    CHECK_UPDATE_REQUEST_APPROVED,
    CHECK_UPDATE_REQUEST_REJECTED,

    NOTE_UPDATE_REQUEST_CREATED,
    NOTE_UPDATE_REQUEST_APPROVED,
    NOTE_UPDATE_REQUEST_REJECTED,

    EXPENSE_ADD
}